config/routes.rb
XantarMultimedia::Application.routes.draw do
  resources :books do
  end

  get 'search' => 'books#search'

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  PER_PAGE = 10
  CATEGORY = {title: "Name", author: "Author", subject: "Subject"}.freeze

  class << self
    def search(params)
      client = Openlibrary::Client.new
      begin
        if params[:category].present?
          client.search({params[:category].to_sym => params[:query]}, page(params), PER_PAGE)
        else
          search_by_priority params, client
        end
      rescue Exception
        nil
      end
    end

    def page params
      params.has_key?(:page) ? params[:page].to_i : 1
    end

    # priorty: author, subject, normal search
    def search_by_priority(params, client)
      books, total = client.search params_find_by_author(params[:query]), page(params), PER_PAGE
      if total == 0
        books, total = client.search params_find_by_subject(params[:query]), page(params), PER_PAGE
      end

      if total == 0
        books, total = client.search params[:query], page(params), PER_PAGE
      end

      [books, total]
    end

    def params_find_by_author(query)
      {author: query}
    end

    def params_find_by_subject(query)
      {subject: query}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = []
  end

  def search
    @books, @total = Book.search params
    render 'index'
  end

  def show
    @book = Openlibrary::Client.new.book(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cover_picture book
    if book && book.edition_key
      edition_key = book.edition_key.first
      image_url = "http://covers.openlibrary.org/b/olid/#{edition_key}-S.jpg"
      return image_url if exist_image_with_edition_key(edition_key)
    end
    '/not_found.jpeg'
  end

  def exist_image_with_edition_key edition_key
    size = FastImage.size "http://covers.openlibrary.org/b/olid/#{edition_key}-S.jpg"
    size && size[0] > 1 && size[1] > 1
  end

  def cover cover
    cover['medium'] if cover
  end

  def published_place places
    address = []
    if places
      address = places.inject([]) { |address, place| address << place['name'] }
    end

    address.join(', ')
  end

  def subjects subjects
    subjects.map { |subject| subject['name'] }.join(', ') if subjects
  end

  def publishers publishers
    publishers.map { |publisher| publisher['name'] }.join(', ') if publishers
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= form_for(@book) do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/books/_search_form.html.haml
= form_tag search_path, method: :get, :html => { :class => 'form-horizontal' } do
  .form-actions
    = text_field_tag :query, params[:query], placeholder: 'Book', class: 'form-control', id: 'query-text-field'
    = select_tag :category, options_for_select(Book::CATEGORY.map { |key, value| [value, key] }, params[:category]), prompt: "Select", class: 'btn'
    = submit_tag 'Go', :class => 'btn btn-primary'

app/views/books/edit.html.haml
%h1 Editing book
= render 'form'
= link_to 'Show', @book
|
\#{link_to 'Back', books_path}

app/views/books/index.html.haml
%h1 Listing books
.search-box
  = render 'search_form'
.paginate.pull-right
  = "#{@total.to_i} results"
  - page = params[:page] || 1
  - next_page = page.to_i + 1
  - previous_page = page.to_i - 1

  - if previous_page > 0
    = link_to "Previous Page", search_path(params.merge(page: page.to_i - 1))
  = "Page #{page}"
  - if next_page <= (@total.to_f/Book::PER_PAGE).ceil
    = link_to "Next Page", search_path(params.merge(page: page.to_i + 1))
%table.table.table-striped
  %thead
    %tr
      %th Cover
      %th Title
      %th Author
      %th Subject
  %tbody
    - if @books
      - @books.each do |book|
        %tr
          %td= image_tag cover_picture(book), alt: book.title
          %td= link_to book.title, book_path(book.edition_key.first)
          %td= book.author_name.join(', ') if book.author_name.is_a? Array
          %td= book.subject.join(', ') if book.subject

app/views/books/new.html.haml
%h1 New book
= render 'form'
= link_to 'Back', books_path

app/views/books/show.html.haml
%h1
  = @book['title']
.cover
  = image_tag cover(@book['cover'])
%h4
  Author:
  - @book['authors'].each do |author|
    = link_to author['name'], author['url']
%h5
  = subjects @book['subjects']
%h5
  Number of pages
  = @book['number_of_pages']
%h5
  Publisher:
  = publishers @book['publishers']
%h5
  Published date:
  = @book['publish_date']
%h5
  Published place:
  = published_place @book['publish_places']
= link_to 'Back', session[:return_to]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Xantar Multimedia
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield